[project]
name = "instafix-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp[speedups]>=3.11.14",
    "aiosqlite>=0.21.0",
    "loguru>=0.7.3",
    "networkx>=3.4.2",
    "pillow>=11.1.0",
    "selectolax[cython]>=0.3.28",
    "tomli>=2.2.1",
    "uvloop>=0.21.0",
]
